mytuple = ("Alan","Ravi","Aswin","Malavika","Sikha")
print(mytuple)
print(type(mytuple))
newtuple = tuple(mytuple)
print(type(newtuple))
print(newtuple[3])
print(newtuple[-1])
print(newtuple[0:3])
print(newtuple[-1:0:-1])